### ISSUE TITLE
production build error on latest ionic

### ISSUE THREAD

**Issue by chmdznr** [arielfaur/ionic-pullup#36]
ionic info:
```
Your system information:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v7.7.3
Xcode version: Xcode 8.2.1 Build version 8C1002
```
step to reproduce:
```

1. ionic start pullup blank --v2
2. cd pullup
3. npm install ionic-pullup
4. edit app.module.ts to include IonPullupModule
5. ionic serve
6. ionic build ios --prod
7. (same error when in android platform)

```

Error messages:
```
[06:01:10]  ionic-app-scripts 1.1.4
[06:01:10]  build prod started ...
[06:01:10]  clean started ...
[06:01:10]  clean finished in 3 ms
[06:01:10]  copy started ...
[06:01:10]  ngc started ...
[06:01:15]  build prod failed: Error encountered resolving symbol values statically. **Calling function
            'makeParamDecorator', function calls are not supported**. Consider replacing the function or lambda with a
            reference to an exported function, resolving symbol Injectable in
            /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/metadata.d.ts,
            resolving symbol OpaqueToken in
            /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/opaque_token.d.ts,
            resolving symbol OpaqueToken in
            /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/opaque_token.d.ts
[06:01:15]  ionic-app-script task: "build"
[06:01:15]  Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function
            calls are not supported. Consider replacing the function or lambda with a reference to an exported function,
            resolving symbol Injectable in
            /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/metadata.d.ts,
            resolving symbol OpaqueToken in
            /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/opaque_token.d.ts,
            resolving symbol OpaqueToken in
            /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/opaque_token.d.ts
Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/USER/Documents/ionic/pullup/node_modules/ionic-pullup/node_modules/@angular/core/src/di/opaque_token.d.ts
    at SyntaxError.BaseError [as constructor] (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:1597:31)
    at new SyntaxError (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at simplifyInContext (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:25783:27)
    at StaticReflector.simplify (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:25795:17)
    at StaticReflector.annotations (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:18272:64)
    at addNgModule (/Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:25053:62)
    at /Users/USER/Documents/ionic/pullup/node_modules/@angular/compiler/bundles/compiler.umd.js:25064:18
    at Array.forEach (native)
```

package.json content:
```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic-native/core": "3.1.0",
    "@ionic-native/splash-screen": "3.1.0",
    "@ionic-native/status-bar": "3.1.0",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.2.0",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "pullup: An Ionic project"
}

```

**build --dev** on latest ionic is fine, no error whatsoever.

**Comment by arielfaur** [comment]
Thanks @chmdznr. This happens since the latest update from Ionic I think.  I will look into it when I find some time.

**Comment by chmdznr** [comment]
Temporary fix:

1. no need to `npm install ionic-pullup --save`. If you already install it, uninstall it first.
2. download/clone the 2.0 branch repo
3. look for "**dist**" folder, you'll find all ion-pullup component source there.
4. create a new folder "**src/components/ionic-pullup/**" in your ionic project
5. now copy all files inside "**dist**" folder to your "**src/components/ionic-pullup/**"
6. edit all import to reflect this new location. So, in your **app.module.ts**, the import statement would be like this: 
`import { IonPullupModule } from '../components/ionic-pullup';`
7. and in your page where you use ionic-pullup, the import statement become like this: 
`import { IonPullUpFooterState } from '../../components/ionic-pullup';`

No code changes needed.
**ionic build --prod** would work as usual (tested on ios and android platform)

**Comment by arielfaur** [comment]
I have just upgraded this module to `3.0.0`. Uninstalling the previous version and installing `3.0.0` should fix this issue.

**Comment by baskin** [comment]
@arielfaur, still occuring .

I'm using latest version
> "ionic-pullup": "^3.0.0",

> ionic info
> global packages:
>     @ionic/cli-utils : 1.2.0
>     Cordova CLI      : 7.0.1 
>     Ionic CLI        : 3.2.0
> local packages:
>     @ionic/app-scripts              : 1.3.7
>     @ionic/cli-plugin-cordova       : 1.3.0
>     @ionic/cli-plugin-ionic-angular : 1.3.0
>     Cordova Platforms               : none
>     Ionic Framework                 : ionic-angular 3.2.1
> System:
>     Node       : v6.9.1
>     OS         : OS X El Capitan


I get the following on running
> > npm run ionic:build --prod

> > everydaynews@0.0.1 ionic:build /Users/bhupi/repo/nooz
> > ionic-app-scripts build
> 
> [21:40:04]  ionic-app-scripts 1.3.7 
> [21:40:04]  build prod started ... 
> [21:40:04]  clean started ... 
> [21:40:04]  clean finished in 3 ms 
> [21:40:04]  copy started ... 
> [21:40:04]  ngc started ... 
> [21:40:15]  ionic-app-script task: "build" 
> [21:40:15]  Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function 
>             calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
>             resolving symbol Injectable in 
>             /Users/bhupi/repo/nooz/node_modules/ionic-pullup/node_modules/@angular/core/core.d.ts, resolving symbol ɵf 
>             in /Users/bhupi/repo/nooz/node_modules/ionic-pullup/node_modules/@angular/core/core.d.ts, resolving symbol 
>             ɵf in /Users/bhupi/repo/nooz/node_modules/ionic-pullup/node_modules/@angular/core/core.d.ts 
> Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/bhupi/repo/nooz/node_modules/ionic-pullup/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/bhupi/repo/nooz/node_modules/ionic-pullup/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/bhupi/repo/nooz/node_modules/ionic-pullup/node_modules/@angular/core/core.d.ts
>     at Error (native)
>     at syntaxError (/Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
>     at simplifyInContext (/Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:23870:23)
>     at StaticReflector.simplify (/Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:23882:13)
>     at StaticReflector.annotations (/Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:23331:41)
>     at NgModuleResolver.resolve (/Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:13883:70)
>     at CompileMetadataResolver.getNgModuleMetadata (/Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:14473:60)
>     at addNgModule (/Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
>     at /Users/bhupi/repo/nooz/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
>     at Array.forEach (native)
>

**Comment by arielfaur** [comment]
@baskin Yes, this is an issue with the latest Ionic 3 update. Every update breaks things :(
I'll have to look into this.

**Comment by kabelo38** [comment]
any news?

**Comment by arielfaur** [comment]
I just fixed this. Version `3.0.1` should work with a production release. Let me know!

**Comment by kabelo38** [comment]
cool will test and provide feedback

Thanks alot

**Comment by fedecoraglio** [comment]
I had the same issue, and now is working fine. Thanks!
